### PR TITLE
Sorted stations by id num and added East Pakenham

### PR DESCRIPTION
**Pull request by pbgcommits**
Added the recently built East Pakenham Station, and also changed the ordering of stations so they're sorted by their stop id. 
:)

### CODE REVIEW

**Comment by stevage** [comment]
Thanks for making this!

I don't want to change the order of the stations though - it will change the meaning of all past games, which I'd prefer not to do.

Are you able to update the PR with just the station addition? (Ideally we'd extend the Pakenham Line slightly in trainline.geojson, but not essential)

**Comment by pbgcommits** [comment]
Great! I've just put East Pakenham at the bottom of stations.json.

For now I'm not going to touch the geojsons as I'm not sure of the best way to update them (I assume that the geojsons have been generated from data from PTV, but it doesn't seem like PTV have released data for East Pakenham yet). 

I can update them manually (it's a straight line from Pakenham to East Pakenham, so I assume I could add a Pakenham - East Pakenham segment with just two coord pairs?), but not sure if that's the best way to do it (or if it would conflict with the Pakenham/Bairnsdale segment) :)

**Comment by pbgcommits** [comment]
Hey mate. I've just tested the code on my machine (which obviously I should have done before committing it to you!) and realised it didn't work. 

I've just updated the stationsForLine() function so it correctly calculates the position of East Pakenham. 

However I'm not sure how to add East Pakenham in a way which doesn't mess with previous games. 
It seems like when stations were last added to the game it was only a few days after the game launched, so it affecting previous games wasn't a big issue?

I have a few possible solutions, let me know if any of them sound reasonable!

Solution 1: Create a stations_v2.json file and change the old one to be named stations_v1.json. Pass the game number to the makeTargets() function in utils, and use the relevant stations_vX.json file depending on the game number. Would need to add a new stations_vX.json file whenever a new station is built (probably not too often!).

Solution 2: Store the list of all game targets in a text file. Update it from the current game number whenever  a new station is built. 

Solution 3: ??

Let me know if you'd be happy for me to implement either of those! Seems like solution 1 would be easier to incorporate into the codebase but not sure what you reckon. Cheers mate

**Comment by pbgcommits** [comment]
Hey mate. I've just tested the code on my machine (which obviously I should have done before committing it to you!) and realised it didn't work.

I've just updated the stationsForLine() function so it correctly calculates the position of East Pakenham.

However I'm not sure how to add East Pakenham in a way which doesn't mess with previous games.
It seems like when stations were last added to the game it was only a few days after the game launched, so it affecting previous games wasn't a big issue?

It seems like the easiest fix would be to make a txt file which lists the solutions (with line num == game num) and just reads the relevant line out of that. Or have a txt file for the first 300 days using the old stations.json and a second txt file generated using the updated json (which could also get rid of Surrey Hills/Mont Albert and put in Union). 

Do either of those sound reasonable to you? I'm just not sure how to avoid it changing the order when a new station is put in otherwise. Cheers mate

**Comment by pbgcommits** [comment]
Hey mate.
I've just added hardcoded solutions in to workaround the issue. It has solutions for the first 36500 games (i.e. we'll be set for a little under a century). 
Seems to work fine but not sure how you feel about having the solutions hardcoded in like that :) Cheers

**Comment by stevage** [comment]
Heh, um.

I think my preferred solution would be to just have different copies of the stations.json, and a lookup saying which one to use for which game numbers.

**Comment by pbgcommits** [comment]
How does that look?

**Comment by stevage** [comment]
Awesome, thanks so much!

**Pull request merged**
